# Generated by Django 5.1.3 on 2024-11-09 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('german', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='learning', max_length=10)),
                ('known_streak', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.word')),
            ],
        ),
    ]
