# Generated by Django 5.1.3 on 2024-11-09 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordstatus',
            name='times_known',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='german',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userwordstatus',
            unique_together={('user', 'word')},
        ),
    ]
