# Generated by Django 5.1.3 on 2024-11-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_userwordstatus_times_known_alter_word_german_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='german',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flashcards.stack'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('german', 'stack')},
        ),
    ]
