# Generated by Django 5.1.3 on 2024-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_remove_stack_description_alter_stack_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='sentence_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
