# Generated by Django 5.1.3 on 2024-11-10 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_word_sentence_word_sentence_translation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='word',
            name='german',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='flashcards.stack'),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=255),
        ),
    ]
