# Generated by Django 5.1.3 on 2024-11-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_word_unique_together_alter_word_german_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stack',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwordstatus',
            name='status',
            field=models.CharField(choices=[('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='learning', max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='german',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('german', 'stack')},
        ),
    ]
